name: baybayay_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.1.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
